# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0003_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='number',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
