# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0004_auto_20190301_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
