# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0005_auto_20190301_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/nofoto.png', upload_to='product_images'),
        ),
    ]
