# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0006_auto_20190302_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='nofoto.png', upload_to='product_images'),
        ),
    ]
