# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0009_auto_20190303_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ProductDiscount', to='pomelo.Product', verbose_name='Produkt')),
            ],
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pomelo.Product', verbose_name='Produkt'),
        ),
    ]
