# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0010_auto_20190304_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
