# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0011_auto_20190304_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='pomelo.Product', verbose_name='Produkt'),
        ),
    ]
