# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0012_auto_20190304_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_images', verbose_name='Image'),
        ),
    ]
