# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0013_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='nofoto.png', null=True, upload_to='category_images', verbose_name='Image'),
        ),
    ]
