# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0015_auto_20190310_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='pomelo.Product', verbose_name='Produkt'),
        ),
    ]
