# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0018_auto_20190316_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
