# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0026_auto_20190316_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(choices=[(10, b'full'), (9, b'half'), (8, b'full'), (7, b'half'), (6, b'full'), (5, b'half'), (4, b'full'), (3, b'half'), (2, b'full'), (1, b'half')], default=10),
        ),
    ]
