# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pomelo', '0029_auto_20190318_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(choices=[(10, b'full'), (9, b'half'), (8, b'full'), (7, b'half'), (6, b'full'), (5, b'half'), (4, b'full'), (3, b'half'), (2, b'full'), (1, b'half')], default=1),
        ),
    ]
